server {
    listen 443 ssl;
    server_name api.internal.ntro.example;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'DES-CBC3-SHA:RC4-SHA:AES128-SHA';
    ssl_certificate     /etc/ssl/certs/expiring-rsa.pem;
    ssl_certificate_key /etc/ssl/private/legacy-rsa.key;
}
